language: python
python:
  - "3.6.4"
services:
  - mongodb
before_install:
  - sudo apt-get update
  - sudo apt-get install make gcc libc-dev libjpeg62-dev python-tk
install: "pip install -r requirements.txt"
script: bash travis.sh 
