version: '3'
services:
  app-server:
    command: >
      gunicorn -b 0.0.0.0:80
      --access-logfile -
      --reload
      "server.app:app"
    container_name: app-server
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - "mongo-db:mongo-db"
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - mongo
  mongo-db:
    image: mongo:latest
    command: mongod --bind_ip  0.0.0.0
    restart: always
    networks:
        - mongo
    ports:
    - "27017:27017"

  mongosetup:
    image: mongo
    volumes:
        - ./dump:/dump
    entrypoint: ["mongorestore", "--host", "mongo-db", "-d", "app-server", "/dump"]
    networks:
        - mongo
networks:
    mongo: